import AppKit
import Observation

@MainActor
@Observable
final class ClipboardMonitor {
    private(set) var items: [ClipboardItem] = []
    var onNewItem: ((ClipboardItem) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let historyLimit = 20

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.pollPasteboard() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func clear() {
        items.removeAll()
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
    }

    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text, .color, .link:
            pasteboard.setString(item.fullText ?? item.title, forType: .string)
        case .image:
            if let imageData = item.imageData {
                pasteboard.setData(imageData, forType: .tiff)
            }
        }
        lastChangeCount = pasteboard.changeCount
    }

    private func pollPasteboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard let item = readCurrentItem() else { return }
        guard items.first != item else { return }

        items.insert(item, at: 0)
        if items.count > historyLimit {
            items.removeLast(items.count - historyLimit)
        }
        onNewItem?(item)

        if item.kind == .link, let url = URL(string: item.title) {
            Task { [weak self] in
                await self?.fetchLinkPreview(for: item.id, url: url)
            }
        }
    }

    private func fetchLinkPreview(for id: UUID, url: URL) async {
        let result = await LinkPreviewFetcher.fetchPreview(for: url)
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        let current = items[index]
        items[index] = ClipboardItem(
            id: current.id,
            kind: current.kind,
            title: current.title,
            subtitle: current.subtitle,
            copiedAt: current.copiedAt,
            thumbnail: result.image,
            fullText: current.fullText,
            imageData: current.imageData,
            linkPreviewTitle: result.title,
            linkFetchFailed: result.image == nil && result.title == nil
        )
    }

    /// Password managers and similar tools mark sensitive copies with these
    /// de facto standard UTIs (https://nspasteboard.org) so well-behaved
    /// clipboard tools skip them instead of surfacing secrets in history.
    private static let sensitivePasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private func readCurrentItem() -> ClipboardItem? {
        if let types = pasteboard.types, !Self.sensitivePasteboardTypes.isDisjoint(with: types) {
            return nil
        }

        if let color = NSColor(from: pasteboard) {
            return ClipboardItem(
                kind: .color,
                title: color.hexString,
                subtitle: "Color · copied",
                copiedAt: Date(),
                thumbnail: nil,
                fullText: nil,
                imageData: nil
            )
        }

        if let imageData = pasteboard.data(forType: .tiff), let image = NSImage(data: imageData) {
            return ClipboardItem(
                kind: .image,
                title: "Image",
                subtitle: "\(Int(image.size.width))×\(Int(image.size.height)) · copied",
                copiedAt: Date(),
                thumbnail: image,
                fullText: nil,
                imageData: imageData
            )
        }

        guard let string = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !string.isEmpty else { return nil }

        if let url = URL(string: string), let scheme = url.scheme, scheme.hasPrefix("http") {
            return ClipboardItem(
                kind: .link,
                title: string,
                subtitle: "Link · copied",
                copiedAt: Date(),
                thumbnail: nil,
                fullText: nil,
                imageData: nil
            )
        }

        let lineCount = string.components(separatedBy: .newlines).count
        let preview = string.count > 80 ? String(string.prefix(80)) + "…" : string
        return ClipboardItem(
            kind: .text,
            title: preview,
            subtitle: lineCount > 1 ? "\(lineCount) lines copied" : "Text copied",
            copiedAt: Date(),
            thumbnail: nil,
            fullText: string,
            imageData: nil
        )
    }
}

private extension NSColor {
    var hexString: String {
        guard let rgb = usingColorSpace(.deviceRGB) else { return "—" }
        let r = Int(rgb.redComponent * 255)
        let g = Int(rgb.greenComponent * 255)
        let b = Int(rgb.blueComponent * 255)
        return String(format: "#%02X%02X%02X", r, g, b)
    }
}
